config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :grades
  resources :tests do
	member do
      get 'grades'
    end
  end
  resources :students, :except => [:index]
  resources :courses do
	member do
      get 'grades'
    end
  end
  
#	devise_scope :user do
#		root to: "devise/sessions#new"
#	end
  
  root  "courses#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :grades]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.order("year desc")
  end

  # GET /courses/1
  # GET /courses/1.json
  def show   
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
		format.html { redirect_to courses_url, notice: 'Course was successfully created.' }
		format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
		format.html { redirect_to courses_url, notice: 'Course was successfully updated.' }
		format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /courses/1/grades
  def grades
	@course.tests.each{|t| t.initialize_grades}
    @tests = @course.tests.order("date")
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:year)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
	<%= simple_form_for(@course) do |f| %>
	  <%= f.error_notification %>

	  <div class="form-inputs">
		<%= f.input :year, :label => "Año",:collection => @course.yearsForCombo, include_blank: false, selected: @course.year || Time.current.year %>
	  </div>

	  <div class="form-actions">
		<%= f.button :submit, "Aceptar", class: 'btn btn-success' %>
		<%= link_to 'Back', courses_path, class: 'btn btn-primary' %>
	  </div>
	<% end %>
</div>

app/views/courses/edit.html.erb
<h1>Modificar Cursada</h1>

<%= render 'form', course: @course %>

app/views/courses/grades.html.erb
<p id="notice"><%= notice %></p>

<h1>Notas de cursada  <%= @course %> </h1>

<% if (@tests.empty?) %>
	<p> No hay examenes asignados a esta cursada </p> 
	<p><%= link_to 'Crear Examen', new_test_path(course: @course.id)  %></p>
<% elsif (@course.empty?)%>
	<p> No hay estudiantes asignados a esta cursada </p> 
	<p><%= link_to 'Cargar Estudiantes', new_student_path(course: @course.id)  %></p>
<% else %> 

	<% @tests.each do |test| %>

	<h3 class="test_data"> 
		
		<a data-toggle="collapse" href="#collapse<%=test.id %>" role="button" aria-expanded="false" aria-controls="collapse<%=test.id %>">
		<%=test.name %>
		</a>
		<span class="additional_data"> Fecha: <%=test.date %></span>
		
	</h3>
	<div class="collapse" id="collapse<%=test.id %>">
	<table class="table table-striped table-bordered results-table">
	  <thead>
		<tr>
		  <th>Legajo</th>
		  <th>Alumno</th>
		  <th>Nota</th>
		  <th>Resultado</th>
		</tr>
	  </thead>

	  <tbody>
		<% if (test.grades.length > 0) %>
			<% test.grades.each do |grade| %>
		  <tr>
			<td><%= grade.student.file_number %></td>
			
			<td><%= grade.student %></td>
			<td><%= grade.grade %></td>
			<td><%= grade.result %></td>
					
		  </tr>
		  <% end %>
		<% end %>
	  </tbody>
	</table>

	<table class="table table-striped table-bordered results-table">
	  <thead>
		<tr>
		  <th>Aprobados</th>
		  <th>Desaprobados</th>
		  <th>Ausentes</th>
		  <th>Porcentaje de aprobación</th>
		</tr>
	  </thead>

	  <tbody>
		  <tr>
			<td><%= test.ammount_passed %></td>
			<td><%= test.ammount_failed %></td>
			<td><%= test.ammount_absent %></td>
			<td><%= test.pass_rate %></td>
		  </tr>
	  </tbody>
	</table>
	</div>
	<% end %>
<% end %>

app/views/courses/index.html.erb
<h1>Cursadas  <%= link_to new_course_path do %><%=fa_icon "plus-circle", title: "Agregar Cursada"%><% end %> </h1>

<table class="table table-striped table-bordered results-table">
  <thead>
    <tr>
      <th>Año</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td width="60%"><%= course.year %></td>
		<td><%= link_to "Ver inscriptos", course %></td>
		<td><%= link_to "Ver Notas", grades_course_path(course) %></td>		
        <td>
        <%= link_to edit_course_path(course) do %><%=fa_icon "edit lg fw", title: "Editar"%><% end %>
        <%= link_to course, method: :delete, data: { confirm: '¿Esta seguro de querer eliminar el curso?' } do %><%=fa_icon "trash lg fw", title: "Borrar"%><% end %>
		</td>
		        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>Nueva Cursada</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<p>
  <h1>Cursada <%= @course.year %></h1>  
</p>

<% if (@course.empty?) %>
<p> No hay estudiantes asignados a esta cursada </p> 
<p><%= link_to 'Cargar Estudiantes', new_student_path(course: @course.id)  %></p>
<% else %>
<table class="table table-striped table-bordered results-table">
  <thead>
    <tr>
      <th colspan="2" class="h4">Estudiantes inscriptos <%= link_to new_student_path(course: @course.id)  do %><%=fa_icon "plus-circle lg", title: "Nuevo estudiante"%><% end %></th>	  
	  
    </tr>
  </thead>

  <tbody>
    <% @course.students.each do |student| %>
      <tr>
        <td width="80%"><%= student %></td>
        <td><%= link_to student  do %><%=fa_icon "eye lg fw", title: "Ver"%><% end %>
        <%= link_to edit_student_path(student) do %><%=fa_icon "edit lg fw", title: "Editar"%><% end %>
        <%= link_to student, method: :delete, data: { confirm: 'Esta seguro de querer eliminar el alumno' } do %><%=fa_icon "trash lg fw", title: "Borrar"%><% end %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %> 