config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :grades
  resources :tests do
	member do
      get 'grades'
    end
  end
  resources :students, :except => [:index]
  resources :courses do
	member do
      get 'grades'
    end
  end
  
#	devise_scope :user do
#		root to: "devise/sessions#new"
#	end
  
  root  "courses#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">


  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
	<% if user_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Cursadas", courses_path, class: "nav-link" %>
      </li>
	  <li class="nav-item">
        <%= link_to "Examenes", tests_path, class: "nav-link" %>
      </li>

    </ul>
	<% end %>
    <ul class="navbar-nav ml-auto" id="ul-login">
      
        <% if user_signed_in? %>
			<li class="nav-item">
	
			  <%= link_to 'Editar Cuenta', edit_user_registration_path, :class => 'nav-link' %> 
			</li>
			<li class="nav-item">
			  <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
			</li>
			<% else %>
			<li class="nav-item">
			  <%= link_to "Registrarse", new_user_registration_path, :class => 'nav-link'  %> 
			</li>
			  <li class="nav-item">
			  <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
			</li>
		<% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTPSRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'default', media: 'all' %>
  </head>

  <body>
	<%= render 'layouts/navbar' %>	
    <div id="content" class="container">
	
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= alert %></p>
			<% end %>
			
			<%= yield %>

    </div>
  </body>
</html>